--- # copy example
- name: copy example
  hosts: web
  user: user
  become: yes
  connection: ssh
  gather_facts: no 
 
  tasks:
   - name: copy abc.txt into /home/user/
     copy: src=files/abc.txt dest=/home/user/ mode=644 owner=user group=user 
