--- # wait for example
- name: Waitfor example
  hosts: web
  user: user
  become: yes
  gather_facts: no
  connection: ssh
 
  tasks:
   - name: install tomcat
     action: yum name=tomcat state=latest update_cache=yes

   - wait_for: 
      port: 8080
      delay: 5
      state: started

   - name: check httpd browser installed or not
     action: yum name=httpd state=present
