--- #DB installation playbook 
- name: Databse host installtion
  hosts: db
  tasks: 
  - name: Installation of mysql server
    apt:
     name: mariadb-server
     state: absent
     update_cache: True 
