--- # task section 
- name: Task defination
  hosts: web
  user: user
  connection: ssh
  gather_facts: no
  become: yes

  vars:
   pkg_name: httpd

  vars_files:
   - conf/author.yaml
   - conf/copywrite.yaml

  tasks:
   - name: installation httpd browser
     action: yum name={{ pkg_name}} state=latest update_cache=yes
