---
- name: Ensure users
  hosts: db
  become: yes
  
  tasks:
  - name: Ensure user is present
    user:
      name: “{{item}}”
      state: present
    loop:
      - dev_user
      - qa_user
      - prod_user
