--- # handeler defination
- name: Handler playbook test
  hosts: web
  user: user
  connection: ssh
  gather_facts: yes
  become: yes
  
  tasks:
  - name: Ensure httpd package is present
    yum:
    name: httpd
    state: latest
  notify: restart_httpd
 
  handlers:
  - name: restart_httpd
    service:
      name: httpd
      state: restart
